# -*- coding: utf-8 -*-
"""CodeToUseAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkH4tvoNKhwlgHYz7BOeC1xwb6_58E7U
"""

# test_sentiment.py

# Step 1: Install required packages
# pip install transformers torch

from transformers import pipeline

# Step 2: Load the fine-tuned model and tokenizer
model_path = "sentiment_model"  # folder containing config.json, tokenizer, model weights

# Load the pipeline
sentiment_pipeline = pipeline("sentiment-analysis", model=model_path, tokenizer=model_path)

# Step 3: Define some test texts
texts = [
    "I absolutely love this product. It's amazing!",
    "This is the worst thing I've ever used.",
    "I'm not sure how I feel about this.",
    "The app is okay, but it crashes sometimes.",
    "Fantastic experience overall, would recommend."
]

# Step 4: Run sentiment analysis
for text in texts:
    result = sentiment_pipeline(text)[0]
    print(f"Text: {text}\nSentiment: {result['label']} (Confidence: {round(result['score'], 3)})\n")